[2025-05-23T18:32:00.850+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T18:32:00.899+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-05-20T00:00:00+00:00 [queued]>
[2025-05-23T18:32:00.916+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-05-20T00:00:00+00:00 [queued]>
[2025-05-23T18:32:00.918+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-23T18:32:00.952+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-20 00:00:00+00:00
[2025-05-23T18:32:00.968+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=715) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-23T18:32:00.972+0000] {standard_task_runner.py:72} INFO - Started process 733 to run task
[2025-05-23T18:32:00.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_pipeline', 'extract_data', 'scheduled__2025-05-20T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpxthxq6jw']
[2025-05-23T18:32:00.973+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask extract_data
[2025-05-23T18:32:01.064+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-05-20T00:00:00+00:00 [running]> on host 1b0fd2a9e72d
[2025-05-23T18:32:01.200+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T00:00:00+00:00'
[2025-05-23T18:32:01.202+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T18:32:01.203+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T18:32:01.204+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-05-23 18:32:00.900744+00:00
[2025-05-23T18:32:01.204+0000] {logging_mixin.py:190} INFO - Dag name:crypto_etl_pipeline and current dag run status:running
[2025-05-23T18:32:01.205+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-23T18:32:02.965+0000] {logging_mixin.py:190} INFO -                       datetime crypto currency          price
0   2025-05-23T18:32:01.256044    BTC      USD  109095.730000
1   2025-05-23T18:32:01.306719    BTC      BRL  617607.324650
2   2025-05-23T18:32:01.359552    ETH      USD    2567.445000
3   2025-05-23T18:32:01.413690    ETH      BRL   14536.402892
4   2025-05-23T18:32:01.453498   USDT      USD       1.000235
5   2025-05-23T18:32:01.498592   USDT      BRL       5.663147
6   2025-05-23T18:32:01.535963    BNB      USD     668.655777
7   2025-05-23T18:32:01.585603    BNB      BRL    3785.759616
8   2025-05-23T18:32:01.746791    XRP      USD       2.361550
9   2025-05-23T18:32:01.908172    XRP      BRL      13.369248
10  2025-05-23T18:32:02.072779   DOGE      USD       0.234850
11  2025-05-23T18:32:02.261511   DOGE      BRL       1.329763
12  2025-05-23T18:32:02.433567    SOL      USD     180.060000
13  2025-05-23T18:32:02.612021    SOL      BRL    1019.454105
14  2025-05-23T18:32:02.766843    DOT      USD       4.731000
15  2025-05-23T18:32:02.941462    DOT      BRL      26.786055
[2025-05-23T18:32:02.970+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract.py", line 28, in extract_crypto_data
    df.to_csv('C:/airflow/data/bronze/crypto_prices_raw.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:32:02.988+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T18:32:02.989+0000] {logging_mixin.py:190} INFO - Task start:2025-05-23 18:32:00.900744+00:00 end:2025-05-23 18:32:02.988050+00:00 duration:2.087306
[2025-05-23T18:32:02.990+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: crypto_etl_pipeline> dagrun:<DagRun crypto_etl_pipeline @ 2025-05-20 00:00:00+00:00: scheduled__2025-05-20T00:00:00+00:00, state:running, queued_at: 2025-05-23 18:31:57.009175+00:00. externally triggered: False>
[2025-05-23T18:32:02.990+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:32:02.991+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=crypto_etl_pipeline, task_id=extract_data, run_id=scheduled__2025-05-20T00:00:00+00:00, execution_date=20250520T000000, start_date=20250523T183200, end_date=20250523T183202
[2025-05-23T18:32:03.512+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-23T18:32:03.514+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 146 for task extract_data (Cannot save file into a non-existent directory: 'C:/***/data/bronze'; 733)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract.py", line 28, in extract_crypto_data
    df.to_csv('C:/airflow/data/bronze/crypto_prices_raw.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:32:03.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T18:32:03.605+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T18:32:03.616+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
